In [1]:
#https://www.bloomberg.com/news/features/2018-04-19/what-bitcoin-is-really-worth-may-no-longer-be-such-a-mystery
#https://docs.coinapi.io/#latest-data
import requests
import json
import pandas as pd 
key = 'C05AA8DB-A5C3-48CE-B784-597295F1C6AF'
url = 'https://rest.coinapi.io/v1/ohlcv/periods'
headers = {'X-CoinAPI-Key' : key}
response = requests.get(url, headers=headers).json()

In [2]:
t=pd.DataFrame(response)
t

   display_name  length_months  length_seconds period_id  unit_count unit_name
0      1 Second              0               1      1SEC           1    second
1     2 Seconds              0               2      2SEC           2    second
2     3 Seconds              0               3      3SEC           3    second
3     4 Seconds              0               4      4SEC           4    second
4     5 Seconds              0               5      5SEC           5    second
5     6 Seconds              0               6      6SEC           6    second
6    10 Seconds              0              10     10SEC          10    second
7    15 Seconds              0              15     15SEC          15    second
8    20 Seconds              0              20     20SEC          20    second
9    30 Seconds              0              30     30SEC          30    second
10     1 Minute              0              60      1MIN           1    minute
11    2 Minutes              0             120      2MIN           2    minute
12    3 Minutes              0             180      3MIN           3    minute
13    4 Minutes              0             240      4MIN           4    minute
14    5 Minutes              0             300      5MIN           5    minute
15    6 Minutes              0             360      6MIN           6    minute
16   10 Minutes              0             600     10MIN          10    minute
17   15 Minutes              0             900     15MIN          15    minute
18   20 Minutes              0            1200     20MIN          20    minute
19   30 Minutes              0            1800     30MIN          30    minute
20       1 Hour              0            3600      1HRS           1      hour
21      2 Hours              0            7200      2HRS           2      hour
22      3 Hours              0           10800      3HRS           3      hour
23      4 Hours              0           14400      4HRS           4      hour
24      6 Hours              0           21600      6HRS           6      hour
25      8 Hours              0           28800      8HRS           8      hour
26     12 Hours              0           43200     12HRS          12      hour
27        1 Day              0           86400      1DAY           1       day
28       2 Days              0          172800      2DAY           2       day
29       3 Days              0          259200      3DAY           3       day
30       5 Days              0          432000      5DAY           5       day
31       7 Days              0          604800      7DAY           7       day
32      10 Days              0          864000     10DAY          10       day
33      1 Month              1               0      1MTH           1     month
34     2 Months              2               0      2MTH           2     month
35     3 Months              3               0      3MTH           3     month
36     4 Months              4               0      4MTH           4     month
37     6 Months              6               0      6MTH           6     month
38       1 Year             12               0      1YRS           1      year
39      2 Years             24               0      2YRS           2      year
40      3 Years             36               0      3YRS           3      year
41      4 Years             48               0      4YRS           4      year
42      5 Years             60               0      5YRS           5      year

In [5]:
####Exchanges
url = 'https://rest.coinapi.io/v1/exchanges'
headers = {'X-CoinAPI-Key' : key}
response = requests.get(url, headers=headers).json()
t=pd.DataFrame(response)

In [6]:
t

,data_end,data_orderbook_end,data_orderbook_start,data_quote_end,data_quote_start,data_start,data_symbols_count,data_trade_count,data_trade_end,data_trade_start,exchange_id,name,website
0,2018-04-26,2018-04-26T20:02:00.7260000Z,2017-12-18T21:50:58.3910192Z,2018-04-26T20:02:00.7260000Z,2017-12-18T21:50:58.3910192Z,2017-09-06,306,4.597591e+08,2018-04-26T20:01:51.3290000Z,2017-09-06T10:29:03.1290000Z,BINANCE,Binance,https://www.binance.com/
1,2018-04-26,2018-04-26T20:02:01.5116309Z,2015-05-17T00:51:32.6370000Z,2018-04-26T20:02:01.5116309Z,2015-05-17T00:51:32.6370000Z,2015-01-14,13,1.359084e+08,2018-04-26T20:01:50.6830000Z,2015-01-14T16:07:05.0000000Z,COINBASE,GDAX,https://www.gdax.com/
2,2018-04-26,2018-04-26T20:02:01.1290062Z,2014-02-24T17:43:05.0000000Z,2018-04-26T20:02:01.1290062Z,2014-02-24T17:43:05.0000000Z,2011-09-13,15,5.165302e+07,2018-04-26T20:01:49.0000000Z,2011-09-13T13:53:36.0000000Z,BITSTAMP,Bitstamp Ltd.,https://www.bitstamp.net/
3,2018-03-09,2018-03-09T23:34:52.5800000Z,2015-02-15T12:53:50.3430000Z,2018-03-09T23:34:52.5800000Z,2015-02-15T12:53:50.3430000Z,2013-06-12,2,2.085401e+09,2018-03-09T23:23:30.4030000Z,2013-06-12T14:24:24.0000000Z,OKCOIN_CNY,OKCoin CNY,https://www.okcoin.cn/
4,2018-04-26,2018-04-26T20:08:42.8322682Z,2017-03-14T20:03:47.4782440Z,2018-04-26T20:08:42.8322682Z,2017-03-14T20:03:47.4782440Z,2017-01-26,352,3.043023e+08,2018-04-26T20:08:44.9200000Z,2017-01-26T19:48:55.0000000Z,BITTREX,Bittrex,https://bittrex.com/
5,2018-04-26,2018-04-26T20:08:38.4918165Z,2016-06-12T11:53:38.1523879Z,2018-04-26T20:08:38.4918165Z,2016-06-12T11:53:38.1523879Z,2016-05-29,173,2.470643e+08,2018-04-26T20:08:53.0000000Z,2016-05-29T15:05:08.0000000Z,POLONIEX,POLONIEX,https://poloniex.com/
6,2018-04-26,2018-04-26T20:08:43.9767429Z,2014-02-24T17:43:05.0000000Z,2018-04-26T20:08:43.9767429Z,2014-02-24T17:43:05.0000000Z,2013-03-31,148,1.947270e+08,2018-04-26T20:08:55.0000000Z,2013-03-31T22:07:48.0000000Z,BITFINEX,Bitfinex,https://www.bitfinex.com/
7,2018-04-26,2018-04-26T20:08:40.2068978Z,2014-07-31T13:05:46.0000000Z,2018-04-26T20:08:40.2068978Z,2014-07-31T13:05:46.0000000Z,2013-10-22,90,1.327600e+08,2018-04-26T20:08:36.6690000Z,2013-10-22T23:09:46.8630000Z,KRAKEN,Kraken,https://www.kraken.com/
8,2018-04-26,2018-04-26T20:02:58.6410000Z,2018-01-24T00:22:17.2456560Z,2018-04-26T20:02:58.6410000Z,2018-01-24T00:22:17.2456560Z,2018-01-22,198,1.256957e+08,2018-04-26T20:02:51.6430000Z,2018-01-22T12:55:12.5650000Z,HUOBIPRO,Huobi Pro,https://www.huobi.pro/
9,2018-04-26,2018-04-26T20:08:43.6329693Z,2017-03-18T22:53:44.4091161Z,2018-04-26T20:08:43.6329693Z,2017-03-18T22:53:44.4091161Z,2013-12-27,623,1.188982e+08,2018-04-26T20:08:52.0000000Z,2013-12-27T08:23:37.0000000Z,HITBTC,HitBTC,https://hitbtc.io/
10,2018-03-09,2018-03-09T23:36:46.2227576Z,2015-03-29T04:20:18.0000000Z,2018-03-09T23:36:46.2227576Z,2015-03-29T04:20:18.0000000Z,2011-06-13,3,1.185004e+08,2018-03-09T23:34:52.2430000Z,2011-06-13T05:13:24.0000000Z,BTCCHINA,BTCCHINA,https://www.btcchina.com/
11,2018-04-26,2018-04-26T20:05:43.1192517Z,2017-09-21T13:50:30.0371289Z,2018-04-26T20:05:43.1192517Z,2017-09-21T13:50:30.0371289Z,2017-09-21,12,9.208615e+07,2018-04-26T20:05:31.0000000Z,2017-09-21T13:43:23.0000000Z,BITHUMB,BITHUMB,https://www.bithumb.com/
12,2018-04-26,2018-04-26T20:05:15.0728270Z,2017-09-21T13:36:45.5891048Z,2018-04-26T20:05:15.0728270Z,2017-09-21T13:36:45.5891048Z,2017-09-20,8,6.309246e+07,2018-04-26T20:05:00.0000000Z,2017-09-20T13:37:21.0000000Z,COINONE,coinone,https://coinone.co.kr/
13,2018-04-26,2018-04-26T20:04:04.6125579Z,2017-12-18T21:01:51.6121385Z,2018-04-26T20:04:04.6125579Z,2017-12-18T21:01:51.6121385Z,2017-12-01,466,5.162225e+07,2018-04-26T20:04:07.0000000Z,2017-12-01T15:26:32.0000000Z,OKEX,OKEx,https://www.okex.com/
14,2018-04-26,2018-04-26T20:08:35.3009085Z,2015-02-15T12:53:46.6330000Z,2018-04-26T20:08:35.3009085Z,2015-02-15T12:53:46.6330000Z,2015-02-14,5,2.012070e+07,2018-04-26T20:06:30.0000000Z,2015-02-14T16:15:05.5900000Z,OKCOIN_USD,OKCoin USD,https://www.okcoin.com/
15,2018-04-26,2018-04-26T17:37:42.5213020Z,2015-05-17T14:57:14.3470000Z,2018-04-26T17:37:42.5213020Z,2015-05-17T14:57:14.3470000Z,2015-05-17,6,1.959520e+07,2018-03-09T23:34:06.0410000Z,2015-05-17T15:04:12.0000000Z,BTCTRADE,BTCTRADE,https://www.btctrade.com/
16,2018-04-26,2018-04-26T20:08:41.0000000Z,2017-03-14T20:04:08.1113853Z,2018-04-26T20:08:41.0000000Z,2017-03-14T20:04:08.1113853Z,2015-09-25,58,1.118527e+07,2018-04-26T20:08:55.0000000Z,2015-09-25T12:34:25.0000000Z,BITMEX,BitMEX,https://www.bitmex.com/
17,2018-04-26,2018-04-26T20:06:13.4708700Z,2017-03-18T22:53:42.0948480Z,2018-04-26T20:06:13.4708700Z,2017-03-18T22:53:42.0948480Z,2015-10-08,3,9.795377e+06,2018-04-26T20:06:21.6960000Z,2015-10-08T13:40:07.8010000Z,GEMINI,Gemini,https://gemini.com/
18,2018-04-26,2018-04-26T20:08:41.3038639Z,2015-05-26T18:24:28.9330000Z,2018-04-26T20:08:41.3038639Z,2015-05-26T18:24:28.9330000Z,2013-08-25,3,2.858355e+06,2018-04-26T20:08:41.0000000Z,2013-08-25T00:21:44.0000000Z,ITBIT,itBit,https://www.itbit.com/
19,2018-03-09,2018-03-09T23:36:52.2077617Z,2015-03-29T21:46:06.2630000Z,2018-03-09T23:36:50.7701113Z,2015-03-29T21:46:06.2630000Z,2015-03-29,2,5.386868e+08,2018-03-09T23:30:18.0330000Z,2015-03-29T21:46:08.7030000Z,HUOBI,Huobi,https://www.huobi.com/
20,2018-03-09,2018-03-09T23:36:54.4892524Z,2014-02-24T17:43:05.0000000Z,2018-03-09T23:36:50.7544837Z,2014-02-24T17:43:05.0000000Z,2011-08-14,24,6.597480e+07,2018-03-09T23:36:51.3410000Z,2011-08-14T14:14:40.0000000Z,BTC-E,BTC-e,https://btc-e.com/
21,2018-04-26,2018-04-26T19:59:44.4018544Z,2017-03-14T20:03:49.1491232Z,2018-04-26T19:59:44.4018544Z,2017-03-14T20:03:49.1491232Z,2014-12-19,2043,6.431587e+07,2018-04-26T19:50:03.0000000Z,2014-12-19T15:12:05.0000000Z,CRYPTOPIA,Cryptopia,https://www.cryptopia.co.nz/
22,2018-04-25,2018-04-25T23:14:07.5189049Z,2017-03-14T20:03:20.5307029Z,2018-04-23T23:12:00.8549107Z,2017-03-14T20:03:20.5307029Z,2017-03-14,1,5.914297e+07,2017-12-18T10:58:56.0000000Z,2017-03-14T20:04:46.0000000Z,COINCHECK,coincheck,https://coincheck.com/
23,2018-04-26,2018-04-26T19:43:46.8893967Z,2017-09-21T13:45:51.3610312Z,2018-04-26T19:43:46.8893967Z,2017-09-21T13:45:51.3610312Z,2016-09-08,229,5.128618e+07,2018-04-26T19:58:33.0000000Z,2016-09-08T12:23:19.0000000Z,LIQUI,Liqui,https://liqui.io/
24,2018-04-26,2018-04-26T19:58:17.2936536Z,2017-03-14T20:04:15.0007802Z,2018-04-26T19:58:17.2936536Z,2017-03-14T20:04:15.0007802Z,2016-02-17,48,4.395687e+07,2018-04-26T19:58:34.0000000Z,2016-02-17T16:38:11.0000000Z,EXMO,EXMO,https://exmo.com/
25,2018-04-24,2018-04-24T17:43:40.7813960Z,2015-05-18T00:17:30.9400000Z,2018-04-19T00:49:12.3062149Z,2015-05-19T14:31:56.5100000Z,2015-05-18,2,3.804492e+07,2018-03-09T22:02:59.0000000Z,2015-05-18T00:17:33.0000000Z,CHBTC,CHBTC,https://www.chbtc.com/
26,2018-04-26,2018-04-26T20:24:47.7168787Z,2017-03-18T22:53:47.5257032Z,2018-04-26T20:24:47.7168787Z,2017-03-18T22:53:47.5257032Z,2015-01-06,3551,1.983298e+07,2018-04-26T20:01:55.0000000Z,2015-01-06T19:51:51.0000000Z,YOBIT,YObit,https://yobit.net/en/
27,2018-04-25,2018-04-25T23:05:55.1236465Z,2017-11-29T01:10:28.2891461Z,2018-04-23T23:04:06.7435356Z,2017-11-29T01:10:28.2891461Z,2017-11-28,3,1.775258e+07,2018-04-25T23:06:03.0000000Z,2017-11-28T21:25:01.0000000Z,BITFLYER,bitFlyer,https://bitflyer.jp/
28,2018-04-25,2018-04-25T23:55:05.4516324Z,2017-12-28T21:48:26.7161574Z,2018-04-23T23:42:07.0741426Z,2017-12-28T21:48:26.7161574Z,2017-12-14,15,1.603174e+07,2018-04-25T23:36:25.0000000Z,2017-12-14T05:11:55.0000000Z,ZAIF,Zaif,https://zaif.jp/
29,2018-04-25,2018-04-25T23:30:06.4340871Z,2017-03-18T22:53:39.4192811Z,2018-04-23T23:24:34.4598002Z,2017-03-18T22:53:39.4192811Z,2013-09-03,4,1.425355e+07,2018-04-25T23:26:10.6940000Z,2013-09-03T06:31:37.0000000Z,KORBIT,Korbit,https://www.korbit.co.kr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,2018-04-25,2018-04-25T23:26:54.4892444Z,2017-03-14T20:04:17.4937751Z,2018-04-23T23:22:12.5650744Z,2017-03-14T20:04:17.4937751Z,2017-03-14,9,1.269830e+06,2018-04-25T23:12:03.0000000Z,2017-03-14T22:00:23.0000000Z,GATECOIN,Gatecoin,https://gatecoin.com/
60,2018-04-19,2018-04-19T09:12:32.4563368Z,2017-03-18T22:53:45.5791610Z,2018-04-19T09:12:32.4563368Z,2017-03-18T22:53:45.5791610Z,2015-06-26,26,1.029303e+06,2018-04-19T16:12:59.0000000Z,2015-06-26T11:19:16.0000000Z,BXINTH,bx.in.th,https://bx.in.th/
61,2018-04-19,2018-04-19T11:38:26.4350131Z,2018-01-24T00:42:46.1912329Z,2018-04-19T11:38:23.3076990Z,2018-01-24T00:42:46.1912329Z,2017-06-19,50,8.829870e+05,2018-04-19T11:36:46.4120000Z,2017-06-19T05:31:08.2600000Z,ALLCOIN,Allcoin,https://www.allcoin.com/
62,2018-04-25,2018-04-25T23:15:59.2447423Z,2017-03-14T20:04:13.3389084Z,2018-04-23T23:13:21.6577442Z,2017-03-14T20:04:13.3389084Z,2017-03-14,2,7.849400e+05,2018-04-25T23:12:52.3440000Z,2017-03-14T20:04:43.2020000Z,COINMATE,Coin Mate,https://coinmate.io/
63,2018-04-26,2018-04-26T19:58:23.9342138Z,2017-12-24T13:03:38.2179565Z,2018-04-26T19:58:23.9342138Z,2017-12-24T13:03:38.2179565Z,2017-10-08,4,6.520890e+05,2018-04-26T19:58:19.0000000Z,2017-10-08T01:12:04.0000000Z,BTCTURK,BTCTurk,https://www.btcturk.com/
64,2018-04-26,2018-04-26T19:59:45.3556318Z,2017-09-21T13:39:33.4870179Z,2018-04-26T19:59:45.3556318Z,2017-09-21T13:39:33.4870179Z,2017-09-16,12,6.436030e+05,2018-04-26T16:11:56.0000000Z,2017-09-16T00:53:48.0000000Z,INDEPENDENTRESERVE,Independent Reserve,https://www.independentreserve.com/
65,2018-04-25,2018-04-25T23:16:03.6089266Z,2017-09-21T13:36:24.9479094Z,2018-04-23T23:13:23.6592019Z,2017-09-21T13:36:24.9479094Z,2017-09-19,4,5.391890e+05,2018-04-25T23:15:09.0000000Z,2017-09-19T11:20:44.0000000Z,COINFLOOR,coinfloor,https://www.coinfloor.co.uk/
66,2018-04-25,2018-04-25T23:26:15.4486408Z,2017-08-29T15:50:33.5497414Z,2018-04-23T23:22:01.2139475Z,2017-08-29T15:50:33.5497414Z,2017-06-07,23,5.149620e+05,2018-04-25T23:24:54.0000000Z,2017-06-07T04:46:35.0000000Z,DSX,DSX,https://dsx.uk
67,2018-04-26,2018-04-26T19:58:37.7333355Z,2017-12-28T21:34:28.8285993Z,2018-04-26T19:58:37.7333355Z,2017-12-28T21:34:28.8285993Z,2017-12-27,66,4.701610e+05,2018-04-26T18:24:13.0000000Z,2017-12-27T12:49:47.0000000Z,ABUCOINS,Abucoins,https://abucoins.com/
68,2018-04-26,2018-04-26T12:49:30.8160000Z,2018-01-24T00:21:32.6002443Z,2018-04-26T12:49:30.8160000Z,2018-01-24T00:21:32.6002443Z,2017-11-29,143,3.260440e+05,2018-04-25T23:22:24.0000000Z,2017-11-29T02:55:41.0000000Z,SOUTHXCHANGE,SouthXchange,https://www.southxchange.com/
69,2018-04-25,2018-04-25T23:08:53.5410000Z,2018-01-24T00:21:29.5498424Z,2018-04-23T23:06:10.8440000Z,2018-01-24T00:21:29.5498424Z,2018-01-24,17,2.966440e+05,2018-04-25T23:00:26.0000000Z,2018-01-24T18:46:55.0000000Z,BTCTRADEUA,BTC Trade UA,https://btc-trade.com.ua/
70,2017-10-13,2017-10-13T11:04:36.2094926Z,2017-03-14T20:03:53.7061506Z,2017-10-13T11:04:34.3376757Z,2017-03-14T20:03:53.7061506Z,2016-03-27,2,2.048370e+05,2017-10-13T10:45:09.0000000Z,2016-03-27T23:17:37.0000000Z,BTCX,bt.cx,https://bt.cx/en/
71,2018-04-26,2018-04-25T23:31:15.9170000Z,2018-01-24T00:21:49.7672137Z,2018-04-23T23:24:47.5670000Z,2018-01-24T00:21:49.7672137Z,2018-01-16,11,1.759270e+05,2018-04-26T05:19:06.0000000Z,2018-01-16T08:05:06.0000000Z,KUNA,Kuna,https://kuna.io/
72,2018-04-25,2018-04-25T23:08:16.5620000Z,2018-01-24T00:21:43.7267644Z,2018-04-23T23:05:59.5500000Z,2018-01-24T00:21:43.7267644Z,2017-12-26,27,1.052570e+05,2018-04-25T23:07:08.7690000Z,2017-12-26T11:45:54.9730000Z,BRAZILIEX,Braziliex,https://braziliex.com/
73,2018-04-09,2018-04-09T08:05:55.8550000Z,2018-01-24T00:21:35.8644461Z,2018-04-09T06:39:22.7580000Z,2018-01-24T00:21:35.8644461Z,2013-01-07,2,9.393000e+04,2018-02-27T04:44:43.0000000Z,2013-01-07T06:17:04.0000000Z,FYBSG,FYB-SG,https://www.fybsg.com/
74,2018-03-09,2018-03-09T23:36:44.2694266Z,2017-03-14T20:04:56.4842821Z,2018-03-09T23:30:06.7432183Z,2017-03-14T20:04:56.4842821Z,2013-09-28,22,8.193000e+04,2017-08-18T16:48:12.0000000Z,2013-09-28T22:40:50.0000000Z,YUNBI,YUNBI,https://yunbi.com/
75,2018-04-25,2018-04-25T23:05:53.1212134Z,2017-08-29T15:47:11.5174742Z,2018-04-23T23:04:01.2644409Z,2017-08-29T15:47:11.5174742Z,2017-08-26,2,5.787100e+04,2018-04-25T22:17:59.0000000Z,2017-08-26T12:22:43.0000000Z,BITKONAN,BitKonan,https://bitkonan.com/
76,2018-04-09,2018-04-09T08:05:46.6351916Z,2018-01-24T00:21:52.7701638Z,2018-04-09T08:05:51.3851943Z,2018-01-24T00:21:52.7701638Z,2013-07-15,1,2.165500e+04,2018-02-26T14:50:15.0000000Z,2013-07-15T20:40:11.0000000Z,FYBSE,FYB-SE,https://www.fybse.se/
77,2018-04-25,2018-04-25T23:08:56.0743196Z,2017-09-21T13:35:08.7798904Z,2018-04-23T14:09:23.6095952Z,2017-09-21T13:35:08.7798904Z,2017-09-20,1,1.879200e+04,2018-04-25T23:08:02.8230000Z,2017-09-20T12:51:00.5840000Z,BTCC,BTCC,https://www.btcc.com/
78,2018-04-25,2018-04-25T23:15:26.7470000Z,2018-01-24T00:21:48.4137019Z,2018-04-23T23:13:15.7400000Z,2018-01-24T00:21:48.4137019Z,2017-09-10,14,1.798800e+04,2018-04-25T22:56:37.0000000Z,2017-09-10T07:59:21.0000000Z,COINGI,Coingi,https://coingi.com/
79,2018-04-25,2018-04-25T23:03:34.8290000Z,2018-01-24T00:42:37.6443449Z,2018-04-23T23:01:02.2140861Z,2018-01-24T00:42:37.6443449Z,2018-01-23,29,1.623000e+04,2018-04-25T05:41:55.0000000Z,2018-01-23T09:58:13.0000000Z,1BTCXE,1Btcxe,https://1btcxe.com/
80,2018-04-25,2018-04-25T23:33:35.2009523Z,2018-01-24T00:24:54.6812361Z,2018-04-23T23:26:47.8900000Z,2018-01-24T00:24:54.6812361Z,2017-01-14,103,1.293500e+04,2018-04-25T21:24:41.0000000Z,2017-01-14T17:43:31.0000000Z,NOVA,Novaexchange,https://novaexchange.com/
81,2018-04-25,2018-04-25T23:05:56.0535987Z,2018-01-24T00:21:31.1076466Z,2018-04-23T23:03:54.8142529Z,2018-01-24T00:21:31.1076466Z,2017-10-12,29,1.255400e+04,2018-04-25T23:03:45.5100000Z,2017-10-12T18:00:10.7250000Z,BITLISH,Bitlish,https://bitlish.com/
82,2018-04-10,2018-04-10T10:47:11.6840000Z,2018-01-24T00:21:45.2925018Z,2018-04-10T05:55:15.8720000Z,2018-01-24T00:21:45.2925018Z,2018-01-24,1,9.861000e+03,2018-04-10T03:54:07.4020000Z,2018-01-24T18:15:31.9200000Z,COINSECURE,Coinsecure,https://coinsecure.in/
83,2018-04-26,2018-04-26T19:59:33.6073483Z,2017-08-29T15:47:11.6744609Z,2018-04-26T19:59:33.6073483Z,2017-08-29T15:47:11.6744609Z,2014-03-29,37,2.249000e+03,2018-03-15T15:25:03.0000000Z,2014-03-29T12:09:48.0000000Z,BITBAY,BitBay,https://www.bitbay.net/
84,2018-04-25,2018-04-25T23:36:50.2961677Z,2017-03-14T20:05:05.6371921Z,2018-04-23T23:13:19.1067052Z,2017-03-14T20:05:05.6371921Z,2015-09-09,1,5.000000e+02,2015-11-23T06:07:39.0000000Z,2015-09-09T03:09:55.0000000Z,VBTC,VBTC.VN,https://vbtc.vn/
85,2018-04-26,2018-04-26T19:58:01.8686629Z,2017-03-18T22:49:13.7742129Z,2018-04-26T19:58:01.8686629Z,2017-03-18T22:49:13.7742129Z,2017-03-18,51,NaN,NaN,NaN,XBTCE,xBTCe,https://www.xbtce.com
86,2018-04-26,2018-04-26T19:53:28.8710000Z,2018-01-24T00:22:13.1677847Z,2018-04-26T19:53:28.8710000Z,2018-01-24T00:22:13.1677847Z,2018-01-24,500,NaN,NaN,NaN,COINEXCHANGE,CoinExchange,https://www.coinexchange.io/
87,2018-04-25,2018-04-25T23:03:31.5851845Z,2018-01-24T00:42:31.5662178Z,2018-04-23T23:02:17.8638625Z,2018-01-24T00:42:31.5662178Z,2018-01-24,13,NaN,NaN,NaN,ANXPRO,ANXPro,https://anxpro.com/
88,2018-04-25,2018-04-25T23:33:34.1383436Z,2018-01-24T00:21:43.8180000Z,2018-04-23T23:27:04.9488996Z,2018-01-24T00:21:43.8180000Z,2018-01-24,115,NaN,NaN,NaN,LYKKE,Lykke,https://www.lykke.com/

In [7]:
###List of IDs
url = 'https://rest.coinapi.io/v1/assets'
headers = {'X-CoinAPI-Key' : key}
response = requests.get(url, headers=headers).json()
assets=pd.DataFrame(response)

In [8]:
assets.head()

,asset_id,data_end,data_orderbook_end,data_orderbook_start,data_quote_end,data_quote_start,data_start,data_symbols_count,data_trade_count,data_trade_end,data_trade_start,name,type_is_crypto
0,BTC,2018-04-26,2018-04-26T20:08:43.9767429Z,2014-02-24T17:43:05.0000000Z,2018-04-26T20:08:43.9767429Z,2014-02-24T17:43:05.0000000Z,2010-07-17,6215,4.083909e+09,2018-04-26T20:08:55.0000000Z,2010-07-17T23:09:17.0000000Z,Bitcoin,1
1,CNY,2018-04-26,2018-04-26T17:37:42.5213020Z,2015-02-11T16:50:54.6130000Z,2018-04-26T17:37:42.5213020Z,2015-02-11T16:50:54.6130000Z,2011-06-13,182,2.825772e+09,2018-04-25T05:41:55.0000000Z,2011-06-13T05:13:24.0000000Z,Yuan Renminbi,0
2,ETH,2018-04-26,2018-04-26T20:11:18.9967562Z,2015-08-10T13:45:07.8130000Z,2018-04-26T20:11:18.9967562Z,2015-08-10T13:45:07.8130000Z,2015-08-10,2170,5.183712e+08,2018-04-26T20:08:53.0000000Z,2015-08-15T06:08:03.0000000Z,Ethereum,1
3,LTC,2018-04-26,2018-04-26T20:08:43.9767429Z,2014-04-20T15:06:34.0000000Z,2018-04-26T20:08:43.9767429Z,2014-04-20T15:06:34.0000000Z,2013-12-06,1018,4.665259e+08,2018-04-26T20:08:52.0000000Z,2013-12-06T22:07:48.5030000Z,Litecoin,1
4,USD,2018-04-26,2018-04-26T20:08:43.9767429Z,2014-02-24T17:43:05.0000000Z,2018-04-26T20:08:43.9767429Z,2014-02-24T17:43:05.0000000Z,2010-07-17,3238,4.613190e+08,2018-04-26T20:08:55.0000000Z,2010-07-17T23:09:17.0000000Z,US Dollar,0

In [54]:
###pull the symbols
url = 'https://rest.coinapi.io/v1/symbols'
headers = {'X-CoinAPI-Key' : key}
response = requests.get(url, headers=headers).json()
symbols=pd.DataFrame(response)
symbols.head()

,asset_id_base,asset_id_quote,data_end,data_orderbook_end,data_orderbook_start,data_quote_end,data_quote_start,data_start,data_trade_end,data_trade_start,exchange_id,future_delivery_time,option_contract_unit,option_exercise_style,option_expiration_time,option_strike_price,option_type_is_call,symbol_id,symbol_type
0,BTC,CNY,2018-03-09,2018-03-09T23:36:52.0514956Z,2015-02-15T13:05:36.1970000Z,2018-03-09T23:34:52.5800000Z,2015-02-15T12:53:50.3430000Z,2013-06-12,2018-03-09T23:23:30.4030000Z,2013-06-12T14:24:24.0000000Z,OKCOIN_CNY,NaN,NaN,NaN,NaN,NaN,NaN,OKCOIN_CNY_SPOT_BTC_CNY,SPOT
1,BTC,CNY,2018-03-09,2018-03-09T23:36:52.2077617Z,2015-03-29T21:46:06.2630000Z,2018-03-09T23:34:52.3340000Z,2015-03-29T21:46:06.2630000Z,2015-03-29,2018-03-09T23:04:38.7830000Z,2015-03-29T21:46:08.7030000Z,HUOBI,NaN,NaN,NaN,NaN,NaN,NaN,HUOBI_SPOT_BTC_CNY,SPOT
2,LTC,CNY,2018-03-09,2018-03-09T23:36:52.2077617Z,2015-02-15T15:51:22.0870000Z,2018-03-09T21:49:58.9190000Z,2015-02-15T12:53:50.4530000Z,2015-02-14,2018-03-09T23:05:40.1990000Z,2015-02-14T16:15:02.2300000Z,OKCOIN_CNY,NaN,NaN,NaN,NaN,NaN,NaN,OKCOIN_CNY_SPOT_LTC_CNY,SPOT
3,BTC,CNY,2018-03-09,2018-03-09T23:36:52.0046152Z,2015-03-29T04:20:18.0000000Z,2018-03-09T23:36:46.2227576Z,2015-03-29T04:20:18.0000000Z,2011-06-13,2018-03-09T21:59:29.2890000Z,2011-06-13T05:13:24.0000000Z,BTCCHINA,NaN,NaN,NaN,NaN,NaN,NaN,BTCCHINA_SPOT_BTC_CNY,SPOT
4,LTC,CNY,2018-03-09,2018-03-09T23:36:46.9728363Z,2015-03-29T21:46:08.7500000Z,2018-03-09T23:36:50.7701113Z,2015-03-29T21:46:08.7500000Z,2015-03-29,2018-03-09T23:30:18.0330000Z,2015-03-29T21:46:52.4070000Z,HUOBI,NaN,NaN,NaN,NaN,NaN,NaN,HUOBI_SPOT_LTC_CNY,SPOT

In [39]:
#Monthly pricing of bitcoin from bitstamp
url = 'https://rest.coinapi.io/v1/ohlcv/BITSTAMP_SPOT_BTC_USD/latest?period_id=1DAY&time_start=2011-01-01T00:00:00&time_end=2018-02-01T00:00:00&limit=100000'
headers = {'X-CoinAPI-Key' : key}
response = requests.get(url, headers=headers).json()
month_btc=pd.DataFrame(response)
month_btc.head(100)

,price_close,price_high,price_low,price_open,time_close,time_open,time_period_end,time_period_start,trades_count,volume_traded
0,9272.98,9387.82,9135.00,9277.32,2018-04-27T16:40:39.0000000Z,2018-04-27T00:00:03.0000000Z,2018-04-28T00:00:00.0000000Z,2018-04-27T00:00:00.0000000Z,22881,7168.507806
1,9274.48,9326.79,8647.29,8855.07,2018-04-26T23:59:58.0000000Z,2018-04-26T00:00:04.0000000Z,2018-04-27T00:00:00.0000000Z,2018-04-26T00:00:00.0000000Z,50129,20042.961722
2,8864.99,9755.53,8751.00,9648.36,2018-04-25T23:59:59.0000000Z,2018-04-25T00:00:00.0000000Z,2018-04-26T00:00:00.0000000Z,2018-04-25T00:00:00.0000000Z,70776,33035.904045
3,9648.00,9737.16,8930.00,8942.00,2018-04-24T23:59:59.0000000Z,2018-04-24T00:00:04.0000000Z,2018-04-25T00:00:00.0000000Z,2018-04-24T00:00:00.0000000Z,49774,20393.622337
4,8946.95,9006.39,8771.22,8781.70,2018-04-23T23:59:44.0000000Z,2018-04-23T00:00:00.0000000Z,2018-04-24T00:00:00.0000000Z,2018-04-23T00:00:00.0000000Z,26994,10286.117715
5,8789.96,9036.52,8760.00,8924.93,2018-04-22T23:59:50.0000000Z,2018-04-22T00:00:02.0000000Z,2018-04-23T00:00:00.0000000Z,2018-04-22T00:00:00.0000000Z,25924,9346.451759
6,8920.71,9023.40,8608.00,8865.78,2018-04-21T23:59:57.0000000Z,2018-04-21T00:00:02.0000000Z,2018-04-22T00:00:00.0000000Z,2018-04-21T00:00:00.0000000Z,38859,15336.307927
7,8861.00,8934.00,8216.90,8273.00,2018-04-20T23:59:59.0000000Z,2018-04-20T00:00:00.0000000Z,2018-04-21T00:00:00.0000000Z,2018-04-20T00:00:00.0000000Z,42441,16059.622671
8,8271.31,8297.99,8074.44,8172.83,2018-04-19T23:59:55.0000000Z,2018-04-19T00:00:04.0000000Z,2018-04-20T00:00:00.0000000Z,2018-04-19T00:00:00.0000000Z,29792,9436.846328
9,8172.84,8235.00,7870.35,7890.87,2018-04-18T23:59:59.0000000Z,2018-04-18T00:00:01.0000000Z,2018-04-19T00:00:00.0000000Z,2018-04-18T00:00:00.0000000Z,26856,9227.204598
10,7890.87,8160.85,7806.81,8054.68,2018-04-17T23:59:46.0000000Z,2018-04-17T00:00:00.0000000Z,2018-04-18T00:00:00.0000000Z,2018-04-17T00:00:00.0000000Z,29746,9277.151215
11,8048.15,8424.99,7905.00,8353.43,2018-04-16T23:59:55.0000000Z,2018-04-16T00:00:02.0000000Z,2018-04-17T00:00:00.0000000Z,2018-04-16T00:00:00.0000000Z,32384,10866.602957
12,8354.22,8417.00,8001.23,8003.39,2018-04-15T23:59:52.0000000Z,2018-04-15T00:00:04.0000000Z,2018-04-16T00:00:00.0000000Z,2018-04-15T00:00:00.0000000Z,27627,7542.840816
13,8000.41,8232.14,7835.00,7885.90,2018-04-14T23:59:48.0000000Z,2018-04-14T00:00:01.0000000Z,2018-04-15T00:00:00.0000000Z,2018-04-14T00:00:00.0000000Z,33079,8935.530715
14,7896.92,8239.33,7753.32,7923.78,2018-04-13T23:59:59.0000000Z,2018-04-13T00:00:01.0000000Z,2018-04-14T00:00:00.0000000Z,2018-04-13T00:00:00.0000000Z,55266,19605.942751
15,7923.78,8069.34,6758.45,6940.94,2018-04-12T23:59:55.0000000Z,2018-04-12T00:00:07.0000000Z,2018-04-13T00:00:00.0000000Z,2018-04-12T00:00:00.0000000Z,67721,19046.738696
16,6940.94,6984.92,6809.26,6824.75,2018-04-11T23:59:57.0000000Z,2018-04-11T00:00:06.0000000Z,2018-04-12T00:00:00.0000000Z,2018-04-11T00:00:00.0000000Z,30341,5829.425345
17,6835.67,6900.00,6653.21,6782.39,2018-04-10T23:59:55.0000000Z,2018-04-10T00:00:00.0000000Z,2018-04-11T00:00:00.0000000Z,2018-04-10T00:00:00.0000000Z,39990,6489.889696
18,6780.10,7175.83,6611.49,7027.26,2018-04-09T23:59:50.0000000Z,2018-04-09T00:00:04.0000000Z,2018-04-10T00:00:00.0000000Z,2018-04-09T00:00:00.0000000Z,44172,10105.283363
19,7027.26,7104.52,6894.80,6904.21,2018-04-08T23:59:58.0000000Z,2018-04-08T00:00:00.0000000Z,2018-04-09T00:00:00.0000000Z,2018-04-08T00:00:00.0000000Z,17425,4352.697942
20,6904.90,7069.13,6600.99,6627.70,2018-04-07T23:59:59.0000000Z,2018-04-07T00:00:08.0000000Z,2018-04-08T00:00:00.0000000Z,2018-04-07T00:00:00.0000000Z,26198,7683.041653
21,6618.33,6850.00,6510.00,6771.30,2018-04-06T23:59:21.0000000Z,2018-04-06T00:00:06.0000000Z,2018-04-07T00:00:00.0000000Z,2018-04-06T00:00:00.0000000Z,29548,8478.418069
22,6771.69,6928.70,6578.95,6799.37,2018-04-05T23:59:49.0000000Z,2018-04-05T00:00:01.0000000Z,2018-04-06T00:00:00.0000000Z,2018-04-05T00:00:00.0000000Z,34561,11894.535978
23,6799.95,7430.00,6710.38,7415.53,2018-04-04T23:59:57.0000000Z,2018-04-04T00:00:04.0000000Z,2018-04-05T00:00:00.0000000Z,2018-04-04T00:00:00.0000000Z,34554,15789.782099
24,7416.27,7506.84,7001.28,7052.75,2018-04-03T23:59:44.0000000Z,2018-04-03T00:00:02.0000000Z,2018-04-04T00:00:00.0000000Z,2018-04-03T00:00:00.0000000Z,44853,16094.892135
25,7052.76,7106.50,6759.96,6816.31,2018-04-02T23:59:59.0000000Z,2018-04-02T00:00:02.0000000Z,2018-04-03T00:00:00.0000000Z,2018-04-02T00:00:00.0000000Z,33936,13635.837846
26,6813.52,7045.71,6427.16,6926.50,2018-04-01T23:59:12.0000000Z,2018-04-01T00:00:08.0000000Z,2018-04-02T00:00:00.0000000Z,2018-04-01T00:00:00.0000000Z,46750,18053.593151
27,6928.62,7231.73,6794.26,6839.63,2018-03-31T23:59:48.0000000Z,2018-03-31T00:00:02.0000000Z,2018-04-01T00:00:00.0000000Z,2018-03-31T00:00:00.0000000Z,41185,11586.029714
28,6850.00,7302.35,6550.00,7086.14,2018-03-30T23:59:50.0000000Z,2018-03-30T00:00:01.0000000Z,2018-03-31T00:00:00.0000000Z,2018-03-30T00:00:00.0000000Z,73091,29110.030523
29,7088.38,7968.00,6914.53,7932.41,2018-03-29T23:59:57.0000000Z,2018-03-29T00:00:05.0000000Z,2018-03-30T00:00:00.0000000Z,2018-03-29T00:00:00.0000000Z,63169,22145.675450
...,...,...,...,...,...,...,...,...,...,...
70,10196.00,10300.00,9707.51,10011.30,2018-02-16T23:59:59.0000000Z,2018-02-16T00:00:01.0000000Z,2018-02-17T00:00:00.0000000Z,2018-02-16T00:00:00.0000000Z,34671,11852.390819
71,10018.00,10234.00,9350.00,9490.98,2018-02-15T23:59:57.0000000Z,2018-02-15T00:00:08.0000000Z,2018-02-16T00:00:00.0000000Z,2018-02-15T00:00:00.0000000Z,55078,21032.993088
72,9490.98,9515.00,8504.57,8504.57,2018-02-14T23:59:58.0000000Z,2018-02-14T00:00:07.0000000Z,2018-02-15T00:00:00.0000000Z,2018-02-14T00:00:00.0000000Z,52310,17464.531069
73,8522.99,8951.89,8360.13,8891.20,2018-02-13T23:59:54.0000000Z,2018-02-13T00:00:03.0000000Z,2018-02-14T00:00:00.0000000Z,2018-02-13T00:00:00.0000000Z,32550,11374.274153
74,8899.00,8995.00,8067.00,8077.25,2018-02-12T23:59:58.0000000Z,2018-02-12T00:00:02.0000000Z,2018-02-13T00:00:00.0000000Z,2018-02-12T00:00:00.0000000Z,37636,15051.874367
75,8067.00,8560.00,7820.00,8560.00,2018-02-11T23:59:36.0000000Z,2018-02-11T00:00:02.0000000Z,2018-02-12T00:00:00.0000000Z,2018-02-11T00:00:00.0000000Z,30826,12801.068869
76,8560.00,9090.80,8170.86,8693.98,2018-02-10T23:59:51.0000000Z,2018-02-10T00:00:01.0000000Z,2018-02-11T00:00:00.0000000Z,2018-02-10T00:00:00.0000000Z,50221,14678.152655
77,8693.98,8779.62,7753.32,8259.42,2018-02-09T23:59:59.0000000Z,2018-02-09T00:00:04.0000000Z,2018-02-10T00:00:00.0000000Z,2018-02-09T00:00:00.0000000Z,48598,18655.945145
78,8259.76,8644.36,7565.50,7588.01,2018-02-08T23:59:55.0000000Z,2018-02-08T00:00:00.0000000Z,2018-02-09T00:00:00.0000000Z,2018-02-08T00:00:00.0000000Z,44023,22738.687936
79,7588.01,8649.00,7213.80,7737.26,2018-02-07T23:59:59.0000000Z,2018-02-07T00:00:00.0000000Z,2018-02-08T00:00:00.0000000Z,2018-02-07T00:00:00.0000000Z,73735,32620.278670
80,7737.37,8150.00,5920.72,6878.65,2018-02-06T23:59:57.0000000Z,2018-02-06T00:00:01.0000000Z,2018-02-07T00:00:00.0000000Z,2018-02-06T00:00:00.0000000Z,128047,70870.319275
81,6874.27,8335.56,6600.00,8190.78,2018-02-05T23:59:52.0000000Z,2018-02-05T00:00:00.0000000Z,2018-02-06T00:00:00.0000000Z,2018-02-05T00:00:00.0000000Z,91907,46519.157499
82,8191.00,9350.09,7825.00,9225.31,2018-02-04T23:59:55.0000000Z,2018-02-04T00:00:02.0000000Z,2018-02-05T00:00:00.0000000Z,2018-02-04T00:00:00.0000000Z,54054,19110.672461
83,9225.86,9491.20,8170.71,8838.29,2018-02-03T23:59:53.0000000Z,2018-02-03T00:00:05.0000000Z,2018-02-04T00:00:00.0000000Z,2018-02-03T00:00:00.0000000Z,56806,16202.362735
84,8838.83,9096.78,7639.80,9010.87,2018-02-02T23:59:53.0000000Z,2018-02-02T00:00:02.0000000Z,2018-02-03T00:00:00.0000000Z,2018-02-02T00:00:00.0000000Z,46733,18553.400977
85,8998.99,10187.56,8455.00,10148.99,2018-02-01T23:59:55.0000000Z,2018-02-01T00:00:00.0000000Z,2018-02-02T00:00:00.0000000Z,2018-02-01T00:00:00.0000000Z,79648,26273.040093
86,10149.00,10324.00,9514.96,9971.00,2018-01-31T23:59:59.0000000Z,2018-01-31T00:00:00.0000000Z,2018-02-01T00:00:00.0000000Z,2018-01-31T00:00:00.0000000Z,39105,12714.416041
87,9971.00,11222.36,9731.20,11162.62,2018-01-30T23:59:59.0000000Z,2018-01-30T00:00:01.0000000Z,2018-01-31T00:00:00.0000000Z,2018-01-30T00:00:00.0000000Z,57337,21071.772121
88,11162.62,11820.01,10991.00,11685.58,2018-01-29T23:59:59.0000000Z,2018-01-29T00:00:02.0000000Z,2018-01-30T00:00:00.0000000Z,2018-01-29T00:00:00.0000000Z,40879,9983.861239
89,11685.58,11989.15,11360.52,11446.54,2018-01-28T23:59:36.0000000Z,2018-01-28T00:00:02.0000000Z,2018-01-29T00:00:00.0000000Z,2018-01-28T00:00:00.0000000Z,42653,9936.098852
90,11446.54,11630.47,10815.84,11093.74,2018-01-27T23:59:54.0000000Z,2018-01-27T00:00:03.0000000Z,2018-01-28T00:00:00.0000000Z,2018-01-27T00:00:00.0000000Z,39789,10300.930509
91,11092.95,11635.00,10263.32,11140.01,2018-01-26T23:59:39.0000000Z,2018-01-26T00:00:02.0000000Z,2018-01-27T00:00:00.0000000Z,2018-01-26T00:00:00.0000000Z,48897,15061.598885
92,11155.54,11741.82,10868.57,11400.98,2018-01-25T23:59:53.0000000Z,2018-01-25T00:00:00.0000000Z,2018-01-26T00:00:00.0000000Z,2018-01-25T00:00:00.0000000Z,38871,10212.844437
93,11400.96,11500.00,10488.13,10848.99,2018-01-24T23:59:59.0000000Z,2018-01-24T00:00:08.0000000Z,2018-01-25T00:00:00.0000000Z,2018-01-24T00:00:00.0000000Z,40383,11572.655867
94,10851.82,11409.87,9927.54,10810.00,2018-01-23T23:59:53.0000000Z,2018-01-23T00:00:00.0000000Z,2018-01-24T00:00:00.0000000Z,2018-01-23T00:00:00.0000000Z,62278,17233.136496
95,10808.99,11910.78,10028.41,11558.87,2018-01-22T23:59:59.0000000Z,2018-01-22T00:00:00.0000000Z,2018-01-23T00:00:00.0000000Z,2018-01-22T00:00:00.0000000Z,64521,17062.998358
96,11558.87,12791.88,11100.00,12782.99,2018-01-21T23:59:59.0000000Z,2018-01-21T00:00:00.0000000Z,2018-01-22T00:00:00.0000000Z,2018-01-21T00:00:00.0000000Z,47832,11598.725068
97,12775.99,13052.12,11515.94,11560.82,2018-01-20T23:59:46.0000000Z,2018-01-20T00:00:03.0000000Z,2018-01-21T00:00:00.0000000Z,2018-01-20T00:00:00.0000000Z,42260,10319.873343
98,11552.00,12050.39,11025.18,11290.90,2018-01-19T23:59:52.0000000Z,2018-01-19T00:00:01.0000000Z,2018-01-20T00:00:00.0000000Z,2018-01-19T00:00:00.0000000Z,49675,13202.749967
99,11247.57,12146.00,10693.00,11199.00,2018-01-18T23:59:56.0000000Z,2018-01-18T00:00:00.0000000Z,2018-01-19T00:00:00.0000000Z,2018-01-18T00:00:00.0000000Z,83331,22187.039518

In [40]:
month_btc

,price_close,price_high,price_low,price_open,time_close,time_open,time_period_end,time_period_start,trades_count,volume_traded
0,9272.98,9387.82,9135.00,9277.32,2018-04-27T16:40:39.0000000Z,2018-04-27T00:00:03.0000000Z,2018-04-28T00:00:00.0000000Z,2018-04-27T00:00:00.0000000Z,22881,7168.507806
1,9274.48,9326.79,8647.29,8855.07,2018-04-26T23:59:58.0000000Z,2018-04-26T00:00:04.0000000Z,2018-04-27T00:00:00.0000000Z,2018-04-26T00:00:00.0000000Z,50129,20042.961722
2,8864.99,9755.53,8751.00,9648.36,2018-04-25T23:59:59.0000000Z,2018-04-25T00:00:00.0000000Z,2018-04-26T00:00:00.0000000Z,2018-04-25T00:00:00.0000000Z,70776,33035.904045
3,9648.00,9737.16,8930.00,8942.00,2018-04-24T23:59:59.0000000Z,2018-04-24T00:00:04.0000000Z,2018-04-25T00:00:00.0000000Z,2018-04-24T00:00:00.0000000Z,49774,20393.622337
4,8946.95,9006.39,8771.22,8781.70,2018-04-23T23:59:44.0000000Z,2018-04-23T00:00:00.0000000Z,2018-04-24T00:00:00.0000000Z,2018-04-23T00:00:00.0000000Z,26994,10286.117715
5,8789.96,9036.52,8760.00,8924.93,2018-04-22T23:59:50.0000000Z,2018-04-22T00:00:02.0000000Z,2018-04-23T00:00:00.0000000Z,2018-04-22T00:00:00.0000000Z,25924,9346.451759
6,8920.71,9023.40,8608.00,8865.78,2018-04-21T23:59:57.0000000Z,2018-04-21T00:00:02.0000000Z,2018-04-22T00:00:00.0000000Z,2018-04-21T00:00:00.0000000Z,38859,15336.307927
7,8861.00,8934.00,8216.90,8273.00,2018-04-20T23:59:59.0000000Z,2018-04-20T00:00:00.0000000Z,2018-04-21T00:00:00.0000000Z,2018-04-20T00:00:00.0000000Z,42441,16059.622671
8,8271.31,8297.99,8074.44,8172.83,2018-04-19T23:59:55.0000000Z,2018-04-19T00:00:04.0000000Z,2018-04-20T00:00:00.0000000Z,2018-04-19T00:00:00.0000000Z,29792,9436.846328
9,8172.84,8235.00,7870.35,7890.87,2018-04-18T23:59:59.0000000Z,2018-04-18T00:00:01.0000000Z,2018-04-19T00:00:00.0000000Z,2018-04-18T00:00:00.0000000Z,26856,9227.204598
10,7890.87,8160.85,7806.81,8054.68,2018-04-17T23:59:46.0000000Z,2018-04-17T00:00:00.0000000Z,2018-04-18T00:00:00.0000000Z,2018-04-17T00:00:00.0000000Z,29746,9277.151215
11,8048.15,8424.99,7905.00,8353.43,2018-04-16T23:59:55.0000000Z,2018-04-16T00:00:02.0000000Z,2018-04-17T00:00:00.0000000Z,2018-04-16T00:00:00.0000000Z,32384,10866.602957
12,8354.22,8417.00,8001.23,8003.39,2018-04-15T23:59:52.0000000Z,2018-04-15T00:00:04.0000000Z,2018-04-16T00:00:00.0000000Z,2018-04-15T00:00:00.0000000Z,27627,7542.840816
13,8000.41,8232.14,7835.00,7885.90,2018-04-14T23:59:48.0000000Z,2018-04-14T00:00:01.0000000Z,2018-04-15T00:00:00.0000000Z,2018-04-14T00:00:00.0000000Z,33079,8935.530715
14,7896.92,8239.33,7753.32,7923.78,2018-04-13T23:59:59.0000000Z,2018-04-13T00:00:01.0000000Z,2018-04-14T00:00:00.0000000Z,2018-04-13T00:00:00.0000000Z,55266,19605.942751
15,7923.78,8069.34,6758.45,6940.94,2018-04-12T23:59:55.0000000Z,2018-04-12T00:00:07.0000000Z,2018-04-13T00:00:00.0000000Z,2018-04-12T00:00:00.0000000Z,67721,19046.738696
16,6940.94,6984.92,6809.26,6824.75,2018-04-11T23:59:57.0000000Z,2018-04-11T00:00:06.0000000Z,2018-04-12T00:00:00.0000000Z,2018-04-11T00:00:00.0000000Z,30341,5829.425345
17,6835.67,6900.00,6653.21,6782.39,2018-04-10T23:59:55.0000000Z,2018-04-10T00:00:00.0000000Z,2018-04-11T00:00:00.0000000Z,2018-04-10T00:00:00.0000000Z,39990,6489.889696
18,6780.10,7175.83,6611.49,7027.26,2018-04-09T23:59:50.0000000Z,2018-04-09T00:00:04.0000000Z,2018-04-10T00:00:00.0000000Z,2018-04-09T00:00:00.0000000Z,44172,10105.283363
19,7027.26,7104.52,6894.80,6904.21,2018-04-08T23:59:58.0000000Z,2018-04-08T00:00:00.0000000Z,2018-04-09T00:00:00.0000000Z,2018-04-08T00:00:00.0000000Z,17425,4352.697942
20,6904.90,7069.13,6600.99,6627.70,2018-04-07T23:59:59.0000000Z,2018-04-07T00:00:08.0000000Z,2018-04-08T00:00:00.0000000Z,2018-04-07T00:00:00.0000000Z,26198,7683.041653
21,6618.33,6850.00,6510.00,6771.30,2018-04-06T23:59:21.0000000Z,2018-04-06T00:00:06.0000000Z,2018-04-07T00:00:00.0000000Z,2018-04-06T00:00:00.0000000Z,29548,8478.418069
22,6771.69,6928.70,6578.95,6799.37,2018-04-05T23:59:49.0000000Z,2018-04-05T00:00:01.0000000Z,2018-04-06T00:00:00.0000000Z,2018-04-05T00:00:00.0000000Z,34561,11894.535978
23,6799.95,7430.00,6710.38,7415.53,2018-04-04T23:59:57.0000000Z,2018-04-04T00:00:04.0000000Z,2018-04-05T00:00:00.0000000Z,2018-04-04T00:00:00.0000000Z,34554,15789.782099
24,7416.27,7506.84,7001.28,7052.75,2018-04-03T23:59:44.0000000Z,2018-04-03T00:00:02.0000000Z,2018-04-04T00:00:00.0000000Z,2018-04-03T00:00:00.0000000Z,44853,16094.892135
25,7052.76,7106.50,6759.96,6816.31,2018-04-02T23:59:59.0000000Z,2018-04-02T00:00:02.0000000Z,2018-04-03T00:00:00.0000000Z,2018-04-02T00:00:00.0000000Z,33936,13635.837846
26,6813.52,7045.71,6427.16,6926.50,2018-04-01T23:59:12.0000000Z,2018-04-01T00:00:08.0000000Z,2018-04-02T00:00:00.0000000Z,2018-04-01T00:00:00.0000000Z,46750,18053.593151
27,6928.62,7231.73,6794.26,6839.63,2018-03-31T23:59:48.0000000Z,2018-03-31T00:00:02.0000000Z,2018-04-01T00:00:00.0000000Z,2018-03-31T00:00:00.0000000Z,41185,11586.029714
28,6850.00,7302.35,6550.00,7086.14,2018-03-30T23:59:50.0000000Z,2018-03-30T00:00:01.0000000Z,2018-03-31T00:00:00.0000000Z,2018-03-30T00:00:00.0000000Z,73091,29110.030523
29,7088.38,7968.00,6914.53,7932.41,2018-03-29T23:59:57.0000000Z,2018-03-29T00:00:05.0000000Z,2018-03-30T00:00:00.0000000Z,2018-03-29T00:00:00.0000000Z,63169,22145.675450
...,...,...,...,...,...,...,...,...,...,...
2368,3.92,3.92,3.92,3.92,2011-10-17T05:59:02.0000000Z,2011-10-17T05:59:02.0000000Z,2011-10-18T00:00:00.0000000Z,2011-10-17T00:00:00.0000000Z,2,10.240000
2369,4.05,4.05,4.05,4.05,2011-10-14T09:16:46.0000000Z,2011-10-14T09:14:03.0000000Z,2011-10-15T00:00:00.0000000Z,2011-10-14T00:00:00.0000000Z,6,96.977513
2370,3.97,3.97,3.93,3.93,2011-10-13T21:15:27.0000000Z,2011-10-13T12:57:14.0000000Z,2011-10-14T00:00:00.0000000Z,2011-10-13T00:00:00.0000000Z,10,109.621766
2371,3.93,3.99,3.93,3.95,2011-10-12T14:07:11.0000000Z,2011-10-12T14:03:53.0000000Z,2011-10-13T00:00:00.0000000Z,2011-10-12T00:00:00.0000000Z,5,79.523525
2372,4.10,4.10,3.98,3.98,2011-10-11T12:17:46.0000000Z,2011-10-11T12:12:54.0000000Z,2011-10-12T00:00:00.0000000Z,2011-10-11T00:00:00.0000000Z,4,78.080000
2373,4.51,4.51,3.99,3.99,2011-10-10T19:54:40.0000000Z,2011-10-10T19:53:39.0000000Z,2011-10-11T00:00:00.0000000Z,2011-10-10T00:00:00.0000000Z,5,132.500000
2374,3.89,3.89,3.89,3.89,2011-10-09T11:52:28.0000000Z,2011-10-09T11:52:28.0000000Z,2011-10-10T00:00:00.0000000Z,2011-10-09T00:00:00.0000000Z,1,11.000000
2375,3.99,4.57,3.99,4.57,2011-10-08T17:38:35.0000000Z,2011-10-08T10:00:31.0000000Z,2011-10-09T00:00:00.0000000Z,2011-10-08T00:00:00.0000000Z,6,56.000000
2376,4.61,4.81,4.59,4.80,2011-10-07T20:14:00.0000000Z,2011-10-07T07:25:45.0000000Z,2011-10-08T00:00:00.0000000Z,2011-10-07T00:00:00.0000000Z,7,94.640000
2377,4.80,4.99,4.80,4.88,2011-10-06T20:11:09.0000000Z,2011-10-06T09:06:40.0000000Z,2011-10-07T00:00:00.0000000Z,2011-10-06T00:00:00.0000000Z,14,170.843549
2378,4.92,6.25,4.80,4.92,2011-10-05T17:12:13.0000000Z,2011-10-05T11:02:50.0000000Z,2011-10-06T00:00:00.0000000Z,2011-10-05T00:00:00.0000000Z,15,113.720000
2379,4.98,5.30,4.80,4.86,2011-10-04T15:04:56.0000000Z,2011-10-04T07:20:19.0000000Z,2011-10-05T00:00:00.0000000Z,2011-10-04T00:00:00.0000000Z,24,142.521622
2380,4.87,4.87,4.83,4.85,2011-10-03T06:48:28.0000000Z,2011-10-03T06:46:43.0000000Z,2011-10-04T00:00:00.0000000Z,2011-10-03T00:00:00.0000000Z,6,30.575950
2381,4.82,4.82,4.81,4.81,2011-09-29T11:46:35.0000000Z,2011-09-29T06:57:04.0000000Z,2011-09-30T00:00:00.0000000Z,2011-09-29T00:00:00.0000000Z,12,46.964500
2382,4.82,4.91,4.82,4.90,2011-09-28T13:18:45.0000000Z,2011-09-28T06:37:03.0000000Z,2011-09-29T00:00:00.0000000Z,2011-09-28T00:00:00.0000000Z,14,83.053326
2383,4.92,4.92,4.85,4.85,2011-09-27T11:36:06.0000000Z,2011-09-27T11:35:56.0000000Z,2011-09-28T00:00:00.0000000Z,2011-09-27T00:00:00.0000000Z,4,24.354500
2384,4.80,6.06,4.80,6.06,2011-09-26T16:44:00.0000000Z,2011-09-26T07:47:05.0000000Z,2011-09-27T00:00:00.0000000Z,2011-09-26T00:00:00.0000000Z,11,39.578463
2385,6.05,6.05,6.05,6.05,2011-09-25T20:15:52.0000000Z,2011-09-25T12:13:23.0000000Z,2011-09-26T00:00:00.0000000Z,2011-09-25T00:00:00.0000000Z,2,12.220000
2386,5.68,5.76,5.68,5.70,2011-09-24T16:18:49.0000000Z,2011-09-24T09:15:29.0000000Z,2011-09-25T00:00:00.0000000Z,2011-09-24T00:00:00.0000000Z,14,90.587066
2387,5.72,5.72,5.70,5.70,2011-09-23T09:09:14.0000000Z,2011-09-23T09:09:02.0000000Z,2011-09-24T00:00:00.0000000Z,2011-09-23T00:00:00.0000000Z,4,20.680037
2388,5.72,5.72,5.68,5.68,2011-09-22T13:32:57.0000000Z,2011-09-22T06:19:59.0000000Z,2011-09-23T00:00:00.0000000Z,2011-09-22T00:00:00.0000000Z,5,43.778422
2389,5.66,5.79,5.66,5.70,2011-09-21T16:47:28.0000000Z,2011-09-21T06:43:16.0000000Z,2011-09-22T00:00:00.0000000Z,2011-09-21T00:00:00.0000000Z,5,17.629322
2390,5.66,5.66,4.92,4.92,2011-09-20T16:38:45.0000000Z,2011-09-20T06:51:41.0000000Z,2011-09-21T00:00:00.0000000Z,2011-09-20T00:00:00.0000000Z,17,89.280711
2391,4.90,4.90,4.90,4.90,2011-09-19T13:47:03.0000000Z,2011-09-19T13:47:03.0000000Z,2011-09-20T00:00:00.0000000Z,2011-09-19T00:00:00.0000000Z,1,20.000000
2392,4.92,4.92,4.81,4.87,2011-09-18T20:11:23.0000000Z,2011-09-18T10:06:49.0000000Z,2011-09-19T00:00:00.0000000Z,2011-09-18T00:00:00.0000000Z,8,119.812800
2393,4.87,4.87,4.87,4.87,2011-09-17T15:32:08.0000000Z,2011-09-17T15:32:08.0000000Z,2011-09-18T00:00:00.0000000Z,2011-09-17T00:00:00.0000000Z,1,0.300000
2394,4.85,4.87,4.80,4.82,2011-09-16T16:13:02.0000000Z,2011-09-16T07:02:06.0000000Z,2011-09-17T00:00:00.0000000Z,2011-09-16T00:00:00.0000000Z,4,39.914007
2395,5.13,5.24,5.00,5.12,2011-09-15T15:11:22.0000000Z,2011-09-15T08:39:33.0000000Z,2011-09-16T00:00:00.0000000Z,2011-09-15T00:00:00.0000000Z,6,80.140795
2396,5.53,5.72,5.52,5.58,2011-09-14T15:42:31.0000000Z,2011-09-14T07:00:00.0000000Z,2011-09-15T00:00:00.0000000Z,2011-09-14T00:00:00.0000000Z,14,61.145984
2397,5.97,6.00,5.65,5.80,2011-09-13T19:34:36.0000000Z,2011-09-13T13:53:36.0000000Z,2011-09-14T00:00:00.0000000Z,2011-09-13T00:00:00.0000000Z,12,58.371382

In [33]:
###Retrieving the GDAX pricing... limit value at 100,000 (max value) and dates between 2016-01-01 and 2018-01-01
url = 'https://rest.coinapi.io/v1/ohlcv/COINBASE_SPOT_BTC_USD/history?period_id=1DAY&time_start=2016-01-01T00:00:00&time_end=2018-02-01T00:00:00&limit=100000'
headers = {'X-CoinAPI-Key' : key}
response = requests.get(url, headers=headers).json()
btc_pricing=pd.DataFrame(response)
btc_pricing.head()

,price_close,price_high,price_low,price_open,time_close,time_open,time_period_end,time_period_start,trades_count,volume_traded
0,435.66,437.15,427.92,430.35,2016-01-01T23:59:01.0000000Z,2016-01-01T00:00:16.0000000Z,2016-01-02T00:00:00.0000000Z,2016-01-01T00:00:00.0000000Z,12169,3863.277451
1,435.40,437.56,432.41,435.67,2016-01-02T23:59:23.1200000Z,2016-01-02T00:00:02.0000000Z,2016-01-03T00:00:00.0000000Z,2016-01-02T00:00:00.0000000Z,11493,3275.441801
2,431.91,435.75,425.02,435.40,2016-01-03T23:59:59.8000000Z,2016-01-03T00:00:37.7930000Z,2016-01-04T00:00:00.0000000Z,2016-01-03T00:00:00.0000000Z,14239,3904.335318
3,433.85,435.79,431.37,431.90,2016-01-04T23:59:54.9330000Z,2016-01-04T00:00:34.1730000Z,2016-01-05T00:00:00.0000000Z,2016-01-04T00:00:00.0000000Z,11331,5893.789223
4,433.34,435.64,430.00,433.84,2016-01-05T23:59:31.3770000Z,2016-01-05T00:00:28.7270000Z,2016-01-06T00:00:00.0000000Z,2016-01-05T00:00:00.0000000Z,13848,5150.109476

In [34]:
len(btc_pricing)

762

In [35]:
btc_pricing

,price_close,price_high,price_low,price_open,time_close,time_open,time_period_end,time_period_start,trades_count,volume_traded
0,435.66,437.15,427.92,430.35,2016-01-01T23:59:01.0000000Z,2016-01-01T00:00:16.0000000Z,2016-01-02T00:00:00.0000000Z,2016-01-01T00:00:00.0000000Z,12169,3863.277451
1,435.40,437.56,432.41,435.67,2016-01-02T23:59:23.1200000Z,2016-01-02T00:00:02.0000000Z,2016-01-03T00:00:00.0000000Z,2016-01-02T00:00:00.0000000Z,11493,3275.441801
2,431.91,435.75,425.02,435.40,2016-01-03T23:59:59.8000000Z,2016-01-03T00:00:37.7930000Z,2016-01-04T00:00:00.0000000Z,2016-01-03T00:00:00.0000000Z,14239,3904.335318
3,433.85,435.79,431.37,431.90,2016-01-04T23:59:54.9330000Z,2016-01-04T00:00:34.1730000Z,2016-01-05T00:00:00.0000000Z,2016-01-04T00:00:00.0000000Z,11331,5893.789223
4,433.34,435.64,430.00,433.84,2016-01-05T23:59:31.3770000Z,2016-01-05T00:00:28.7270000Z,2016-01-06T00:00:00.0000000Z,2016-01-05T00:00:00.0000000Z,13848,5150.109476
5,430.87,433.46,428.15,433.32,2016-01-06T23:59:55.6670000Z,2016-01-06T00:00:01.6200000Z,2016-01-07T00:00:00.0000000Z,2016-01-06T00:00:00.0000000Z,15951,5476.959959
6,459.07,460.15,430.64,430.66,2016-01-07T23:59:59.0570000Z,2016-01-07T00:00:02.2870000Z,2016-01-08T00:00:00.0000000Z,2016-01-07T00:00:00.0000000Z,29221,13907.201729
7,454.44,464.40,447.53,459.07,2016-01-08T23:59:32.7770000Z,2016-01-08T00:00:02.2970000Z,2016-01-09T00:00:00.0000000Z,2016-01-08T00:00:00.0000000Z,20050,8341.783440
8,450.38,456.00,447.66,454.41,2016-01-09T23:59:10.8700000Z,2016-01-09T00:00:12.5570000Z,2016-01-10T00:00:00.0000000Z,2016-01-09T00:00:00.0000000Z,18769,4241.356651
9,449.99,451.39,442.96,450.39,2016-01-10T23:59:40.1370000Z,2016-01-10T00:00:01.6270000Z,2016-01-11T00:00:00.0000000Z,2016-01-10T00:00:00.0000000Z,11582,3954.322400
10,449.19,452.65,445.88,449.99,2016-01-11T23:59:40.8770000Z,2016-01-11T00:00:14.2300000Z,2016-01-12T00:00:00.0000000Z,2016-01-11T00:00:00.0000000Z,15254,5597.637183
11,434.01,449.44,431.83,449.26,2016-01-12T23:59:57.8070000Z,2016-01-12T00:00:11.2070000Z,2016-01-13T00:00:00.0000000Z,2016-01-12T00:00:00.0000000Z,13955,6542.947436
12,432.77,437.50,425.00,434.01,2016-01-13T23:59:59.1330000Z,2016-01-13T00:00:01.4170000Z,2016-01-14T00:00:00.0000000Z,2016-01-13T00:00:00.0000000Z,21484,9000.370696
13,430.03,435.27,428.00,432.70,2016-01-14T23:59:59.4270000Z,2016-01-14T00:00:02.3400000Z,2016-01-15T00:00:00.0000000Z,2016-01-14T00:00:00.0000000Z,12068,5673.632962
14,357.53,430.29,357.30,430.04,2016-01-15T23:59:51.5800000Z,2016-01-15T00:00:01.0930000Z,2016-01-16T00:00:00.0000000Z,2016-01-15T00:00:00.0000000Z,42696,28641.673586
15,388.70,391.00,350.92,357.59,2016-01-16T23:59:38.7000000Z,2016-01-16T00:00:00.4600000Z,2016-01-17T00:00:00.0000000Z,2016-01-16T00:00:00.0000000Z,28648,17985.238784
16,378.46,391.00,372.00,388.70,2016-01-17T23:59:51.6930000Z,2016-01-17T00:00:06.8870000Z,2016-01-18T00:00:00.0000000Z,2016-01-17T00:00:00.0000000Z,11965,8278.401793
17,384.89,386.10,370.10,378.47,2016-01-18T23:59:43.8000000Z,2016-01-18T00:00:01.4800000Z,2016-01-19T00:00:00.0000000Z,2016-01-18T00:00:00.0000000Z,20289,8711.459756
18,375.27,385.50,370.00,384.79,2016-01-19T23:59:35.0630000Z,2016-01-19T00:00:08.6970000Z,2016-01-20T00:00:00.0000000Z,2016-01-19T00:00:00.0000000Z,16189,8133.367010
19,418.54,425.10,369.00,375.28,2016-01-20T23:59:41.6500000Z,2016-01-20T00:00:00.9170000Z,2016-01-21T00:00:00.0000000Z,2016-01-20T00:00:00.0000000Z,26750,13867.591226
20,409.38,424.78,403.21,418.89,2016-01-21T23:59:31.2470000Z,2016-01-21T00:00:02.8870000Z,2016-01-22T00:00:00.0000000Z,2016-01-21T00:00:00.0000000Z,17927,8739.163419
21,382.90,413.99,373.86,409.02,2016-01-22T23:59:40.0270000Z,2016-01-22T00:00:30.2030000Z,2016-01-23T00:00:00.0000000Z,2016-01-22T00:00:00.0000000Z,19309,13430.103039
22,387.50,398.72,382.55,382.93,2016-01-23T23:52:33.5130000Z,2016-01-23T00:00:01.3870000Z,2016-01-24T00:00:00.0000000Z,2016-01-23T00:00:00.0000000Z,10997,6310.030022
23,403.05,406.93,387.49,387.50,2016-01-24T23:59:29.8930000Z,2016-01-24T00:02:57.4170000Z,2016-01-25T00:00:00.0000000Z,2016-01-24T00:00:00.0000000Z,3871,3550.831772
24,391.40,403.04,386.41,403.04,2016-01-25T23:59:31.1570000Z,2016-01-25T00:01:22.3000000Z,2016-01-26T00:00:00.0000000Z,2016-01-25T00:00:00.0000000Z,7996,6491.999812
25,391.54,397.00,387.78,391.40,2016-01-26T23:59:31.7000000Z,2016-01-26T00:00:01.5100000Z,2016-01-27T00:00:00.0000000Z,2016-01-26T00:00:00.0000000Z,8820,6947.196367
26,394.79,397.18,390.70,391.70,2016-01-27T23:59:01.4230000Z,2016-01-27T00:00:01.7300000Z,2016-01-28T00:00:00.0000000Z,2016-01-27T00:00:00.0000000Z,12536,6324.164190
27,379.61,395.00,377.12,394.60,2016-01-28T23:59:31.3670000Z,2016-01-28T00:00:01.6200000Z,2016-01-29T00:00:00.0000000Z,2016-01-28T00:00:00.0000000Z,27964,9072.852047
28,378.68,385.05,363.25,379.63,2016-01-29T23:59:31.0170000Z,2016-01-29T00:00:01.4530000Z,2016-01-30T00:00:00.0000000Z,2016-01-29T00:00:00.0000000Z,23039,12105.310437
29,378.46,382.04,375.00,378.68,2016-01-30T23:59:31.5730000Z,2016-01-30T00:00:01.6700000Z,2016-01-31T00:00:00.0000000Z,2016-01-30T00:00:00.0000000Z,14427,4154.296422
...,...,...,...,...,...,...,...,...,...,...
732,14781.51,15275.00,13005.00,13480.00,2018-01-02T23:59:59.0390000Z,2018-01-02T00:00:03.5840000Z,2018-01-03T00:00:00.0000000Z,2018-01-02T00:00:00.0000000Z,175230,26342.451377
733,15098.14,15400.00,14628.00,14781.52,2018-01-03T23:59:55.6840000Z,2018-01-03T00:00:00.0350000Z,2018-01-04T00:00:00.0000000Z,2018-01-03T00:00:00.0000000Z,139559,17864.506554
734,15144.99,15400.00,14230.00,15098.23,2018-01-04T23:59:58.9930000Z,2018-01-04T00:00:01.5950000Z,2018-01-05T00:00:00.0000000Z,2018-01-04T00:00:00.0000000Z,143509,19918.787967
735,16960.01,17178.00,14819.78,15145.00,2018-01-05T23:59:59.9010000Z,2018-01-05T00:00:01.0320000Z,2018-01-06T00:00:00.0000000Z,2018-01-05T00:00:00.0000000Z,165297,22907.890740
736,17098.99,17174.00,16251.01,16960.01,2018-01-06T23:59:59.9940000Z,2018-01-06T00:00:02.9460000Z,2018-01-07T00:00:00.0000000Z,2018-01-06T00:00:00.0000000Z,151647,14096.204305
737,16174.22,17115.01,15755.01,17099.00,2018-01-07T23:59:59.8460000Z,2018-01-07T00:00:00.6420000Z,2018-01-08T00:00:00.0000000Z,2018-01-07T00:00:00.0000000Z,100508,12231.883054
738,14993.74,16275.00,14000.00,16174.22,2018-01-08T23:59:51.0970000Z,2018-01-08T00:00:00.6760000Z,2018-01-09T00:00:00.0000000Z,2018-01-08T00:00:00.0000000Z,158639,23141.295927
739,14480.99,15384.00,14230.00,14993.73,2018-01-09T23:59:59.6720000Z,2018-01-09T00:00:01.8720000Z,2018-01-10T00:00:00.0000000Z,2018-01-09T00:00:00.0000000Z,119891,15318.158058
740,14875.00,14875.18,13550.01,14481.00,2018-01-10T23:59:59.2200000Z,2018-01-10T00:00:02.4490000Z,2018-01-11T00:00:00.0000000Z,2018-01-10T00:00:00.0000000Z,174360,22589.612586
741,13308.06,14970.00,12800.01,14875.17,2018-01-11T23:59:57.3450000Z,2018-01-11T00:00:02.0640000Z,2018-01-12T00:00:00.0000000Z,2018-01-11T00:00:00.0000000Z,156713,28702.248192
742,13820.00,14080.83,12900.00,13308.06,2018-01-12T23:59:58.2580000Z,2018-01-12T00:00:01.7980000Z,2018-01-13T00:00:00.0000000Z,2018-01-12T00:00:00.0000000Z,80380,12872.866431
743,14187.95,14500.00,13792.25,13820.00,2018-01-13T23:59:58.5030000Z,2018-01-13T00:00:00.0820000Z,2018-01-14T00:00:00.0000000Z,2018-01-13T00:00:00.0000000Z,66551,9200.133488
744,13656.23,14332.85,13110.00,14187.94,2018-01-14T23:59:54.0170000Z,2018-01-14T00:00:01.5980000Z,2018-01-15T00:00:00.0000000Z,2018-01-14T00:00:00.0000000Z,73588,10194.522136
745,13590.00,14253.00,13416.00,13656.23,2018-01-15T23:59:59.9570000Z,2018-01-15T00:00:06.8400000Z,2018-01-16T00:00:00.0000000Z,2018-01-15T00:00:00.0000000Z,64751,10490.815145
746,11570.01,13643.66,9928.62,13590.00,2018-01-16T23:59:57.3440000Z,2018-01-16T00:00:00.9300000Z,2018-01-17T00:00:00.0000000Z,2018-01-16T00:00:00.0000000Z,274578,61986.865286
747,11200.01,12358.89,9005.00,11570.01,2018-01-17T23:59:59.0370000Z,2018-01-17T00:00:00.1330000Z,2018-01-18T00:00:00.0000000Z,2018-01-17T00:00:00.0000000Z,240575,63822.849362
748,11305.53,12123.10,10687.21,11204.64,2018-01-18T23:59:54.7970000Z,2018-01-18T00:00:01.0460000Z,2018-01-19T00:00:00.0000000Z,2018-01-18T00:00:00.0000000Z,122337,30083.348050
749,11498.99,11973.99,11050.00,11305.53,2018-01-19T23:59:45.6760000Z,2018-01-19T00:00:00.2550000Z,2018-01-20T00:00:00.0000000Z,2018-01-19T00:00:00.0000000Z,70394,15949.502504
750,12762.80,12985.55,11498.99,11499.00,2018-01-20T23:59:58.1370000Z,2018-01-20T00:00:01.8260000Z,2018-01-21T00:00:00.0000000Z,2018-01-20T00:00:00.0000000Z,85226,18682.400004
751,11518.17,12762.80,11118.00,12762.80,2018-01-21T23:59:59.8740000Z,2018-01-21T00:00:03.2000000Z,2018-01-22T00:00:00.0000000Z,2018-01-21T00:00:00.0000000Z,78114,16374.887611
752,10766.70,11849.00,10025.00,11518.17,2018-01-22T23:59:59.3440000Z,2018-01-22T00:00:01.7030000Z,2018-01-23T00:00:00.0000000Z,2018-01-22T00:00:00.0000000Z,105908,24278.443016
753,10824.94,11370.00,9945.00,10766.70,2018-01-23T23:59:56.0870000Z,2018-01-23T00:00:03.6060000Z,2018-01-24T00:00:00.0000000Z,2018-01-23T00:00:00.0000000Z,98261,21851.085135
754,11356.79,11450.00,10450.00,10824.95,2018-01-24T23:59:59.0260000Z,2018-01-24T00:00:01.7600000Z,2018-01-25T00:00:00.0000000Z,2018-01-24T00:00:00.0000000Z,101164,15100.774119
755,11118.00,11690.00,10851.00,11356.80,2018-01-25T23:59:58.8770000Z,2018-01-25T00:00:01.3690000Z,2018-01-26T00:00:00.0000000Z,2018-01-25T00:00:00.0000000Z,84771,13716.622689
756,11086.89,11570.00,10305.00,11118.00,2018-01-26T23:59:55.1760000Z,2018-01-26T00:00:00.1730000Z,2018-01-27T00:00:00.0000000Z,2018-01-26T00:00:00.0000000Z,89835,19230.729536
757,11319.00,11494.08,10850.00,11086.88,2018-01-27T23:59:58.0820000Z,2018-01-27T00:00:00.3840000Z,2018-01-28T00:00:00.0000000Z,2018-01-27T00:00:00.0000000Z,66368,12243.988688
758,11536.00,11697.24,11234.38,11319.00,2018-01-28T23:59:59.5130000Z,2018-01-28T00:00:01.4220000Z,2018-01-29T00:00:00.0000000Z,2018-01-28T00:00:00.0000000Z,92085,13654.283983
759,11123.01,11570.00,10840.00,11536.00,2018-01-29T23:59:57.2610000Z,2018-01-29T00:00:05.5820000Z,2018-01-30T00:00:00.0000000Z,2018-01-29T00:00:00.0000000Z,72697,11072.720804
760,9995.00,11150.00,9711.11,11123.01,2018-01-30T23:59:58.7880000Z,2018-01-30T00:00:02.4050000Z,2018-01-31T00:00:00.0000000Z,2018-01-30T00:00:00.0000000Z,116560,27349.504519
761,10099.99,10299.95,9601.02,9995.00,2018-01-31T23:59:56.7000000Z,2018-01-31T00:00:01.8880000Z,2018-02-01T00:00:00.0000000Z,2018-01-31T00:00:00.0000000Z,99577,19484.660165